version: "3.3"

services:
  backend:
    image: stasshdev/noteorganizer-backend
    container_name: backend
    working_dir: /backend
    command: node server/index.js
    ports:
      - "5000:5000"
  

  frontend:
    image: stasshdev/noteorganizer-frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend