name: deploy_on_server
on: [ push ]

jobs:
  build:
    runs-on: self-hosted
    environment: deploy
    steps:
    - name: login
      run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USER}} --password-stdin

    - uses: actions/checkout@v4

    - name: Build the Docker image(frontend)
      run: docker build -t ${{secrets.DOCKER_USER}}/noteorganizer-frontend ./frontend

    - name: Push the Docker image(frontend)
      run: docker push ${{secrets.DOCKER_USER}}/noteorganizer-frontend

    - name: Build the Docker image(backend)
      run: docker build -t ${{secrets.DOCKER_USER}}/noteorganizer-backend ./backend

    - name: Push the Docker image(backend)
      run: docker push ${{secrets.DOCKER_USER}}/noteorganizer-backend
    
  deploy:
    runs-on: self-hosted
    environment: deploy
    needs: build
    steps:
    - name: Pull and Up Docker-image
      run: |
        cd ~/AppTest
        docker-compose pull
        docker-compose up -d
