name: deploy_on_server
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
    - name: login
      run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USER}} --password-stdin

    - uses: actions/checkout@v4

    - name: Build the Docker image(frontend)
      run: docker build ${{secrets.DOCKER_USER}}/noteorganizer-frontend ./frontend

    - name: Push the Docker image(frontend)
      run: docker push ${{secrets.DOCKER_USER}}/noteorganizer-frontend

    - name: Build the Docker image(backend)
      run: docker build ${{secrets.DOCKER_USER}}/noteorganizer-backend ./backend

    - name: Push the Docker image(backend)
      run: docker push ${{secrets.DOCKER_USER}}/noteorganizer-backend
    
  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    needs: build
    steps:
    - uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.SSH_HOST}}
        username: ${{secrets.SSH_USER}}
        password: ${{secrets.SSH_PASSWORD}}
        port: 22
        script: |
          cd ~/AppTest
          sudo docker-compose up -d
